<html>
	<head>

	<link href="static/css/slider.css" rel="stylesheet">
	<link href="static/css/main.css" rel="stylesheet">
	<link href="static/css/lol.css" rel="stylesheet">

	</head>

	<body>
	<main id="top" class="masthead" role="main">
		<a href='/demo'>
			<div class="logo"><img src="/static/images/logo_4.png" alt="logo" >
		</a>	
		<form action="/video" method="POST" enctype="multipart/form-data">
			<center>
				<input class= "myButton2" type="file" name="uploaded_file" value="Upload"/>
				<input class= "myButton" type="submit" name="submitb" value="Go"/>
			</center>
		</form>
		<br/>

    <!-- #region Jssor Slider Begin -->

    <!-- Generated by Jssor Slider Maker Online. -->
    <!-- This demo works with jquery library -->

    <script type="text/javascript" src="static/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="static/js/jssor.slider.mini.js"></script>
    <!-- use jssor.slider.debug.js instead for debug -->
    <script>
        jQuery(document).ready(function ($) {
            
            var jssor_1_SlideshowTransitions = [
          ];
            
            var jssor_1_SlideoTransitions = [
              [{b:-1,d:1,rY:90},{b:8500,d:1000,o:-1,rY:-90}],
              [{b:-1,d:1,o:-1},{b:0,d:640,x:-300,o:1},{b:1000,d:500,x:-370}],
              [{b:640,d:520,x:100,y:-320}],
              [{b:1500,d:500,y:250},{b:8500,d:1000,x:600}],
              [{b:-1,d:1,o:-1,sX:-0.6,sY:-0.6},{b:2000,d:500,o:1,r:360,sX:0.6,sY:0.6},{b:8500,d:1000,y:-150}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:2500,d:1000,o:1,tZ:200},{b:3500,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:3500,d:1000,o:1,tZ:200},{b:4500,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:4500,d:1000,o:1,tZ:200},{b:5500,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:5500,d:1000,o:1,tZ:200},{b:6500,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:6500,d:1000,o:1,tZ:200},{b:7500,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:7500,d:1000,o:1,tZ:200},{b:8500,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,c:{x:250.0,t:-250.0}},{b:0,d:1000,c:{x:-250.0,t:250.0}},{b:5000,d:1000,y:100}],
              [{b:-1,d:1,o:-1},{b:1000,d:1000,o:1},{b:5000,d:1000,y:280}],
              [{b:2000,d:1000,y:190,e:{y:28}},{b:5000,d:1000,x:280}],
              [{b:3000,d:520,y:50},{b:5000,d:1000,y:-50}],
              [{b:3520,d:640,x:-400},{b:5000,d:800,x:400,e:{x:7}}],
              [{b:4000,d:500,x:-400},{b:5000,d:800,x:400,e:{x:7}}],
              [{b:4500,d:500,x:-400},{b:5000,d:800,x:400,e:{x:7}}],
              [{b:-1,d:1,o:-0.4},{b:0,d:1000,y:140,o:0.4},{b:23000,d:1000,y:-140}],
              [{b:-1,d:1,c:{x:275.0,t:-275.0}},{b:1000,d:1000,c:{x:-275.0,t:275.0}},{b:23000,d:1000,y:100}],
              [{b:-1,d:1,o:-1},{b:2000,d:1000,o:1},{b:23000,d:1000,o:-1}],
              [{b:-1,d:1,sX:-0.7,sY:-0.7},{b:5000,d:1000,sX:0.4,sY:0.4,e:{sX:16,sY:16}},{b:9000,d:1000,sX:-0.2,sY:-0.2,e:{sX:16,sY:16}},{b:13000,d:1000,sX:-0.3,sY:-0.3,e:{sX:16,sY:16}},{b:17000,d:1000,sX:0.4,sY:0.4,e:{sX:16,sY:16}},{b:21000,d:1000,sX:0.4,sY:0.4,e:{sX:16,sY:16}}],
              [{b:4000,d:1500,x:195,y:450,r:-90},{b:8000,d:1500,x:-225,y:-240,r:-90},{b:12000,d:1500,x:-220,y:-1140,r:120},{b:16000,d:1500,x:400,y:580,r:100},{b:20000,d:1500,x:350,y:350,r:90}],
              [{b:4000,d:1500,o:-0.6}],
              [{b:-1,d:1,o:-0.6,r:90},{b:4000,d:1500,o:0.6},{b:8000,d:1500,o:-0.6}],
              [{b:-1,d:1,o:-0.6,r:180},{b:8000,d:1500,o:0.6},{b:12000,d:1500,o:-0.6}],
              [{b:-1,d:1,o:-0.6,r:60},{b:12000,d:1500,o:0.6},{b:16000,d:1000,o:-0.6}],
              [{b:-1,d:1,o:-0.6,r:-40},{b:16000,d:1000,o:0.6},{b:20000,d:1500,o:-0.6}],
              [{b:-1,d:1,o:-0.6,r:-130},{b:20000,d:1500,o:0.6}],
              [{b:-1,d:1,c:{x:250.0,t:-250.0}},{b:0,d:1000,c:{x:-250.0,t:250.0}},{b:10000,d:500,y:90}],
              [{b:-1,d:1,c:{x:150.0,t:-150.0}},{b:1000,d:1000,c:{x:-150.0,t:150.0}},{b:10000,d:500,c:{y:150.0,m:-150.0}}],
              [{b:2000,d:500,x:220}],
              [{b:3500,d:500,rX:-20},{b:4000,d:1000,rX:40},{b:5000,d:500,rX:-10},{b:9500,d:500,o:-1}],
              [{b:3500,d:2000,r:360}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,x:76,y:-25,o:1}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,x:47,y:65,o:1}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,x:-47,y:65,o:1}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,x:-76,y:-25,o:1}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,y:-80,o:1}],
              [{b:-1,d:1,c:{x:120.0,t:-120.0}},{b:6100,d:400,c:{x:-120.0,t:120.0}},{b:10000,d:500,y:-120}],
              [{b:6500,d:500,x:220}],
              [{b:-1,d:1,o:-1,r:180,sX:-0.5,sY:-0.5},{b:7000,d:500,o:1,r:180,sX:0.5,sY:0.5},{b:8000,d:500,o:-1,r:180,sX:9,sY:9}],
              [{b:-1,d:1,o:-1,r:180,sX:-0.5,sY:-0.5},{b:8000,d:500,o:1,r:180,sX:0.5,sY:0.5},{b:9000,d:500,o:-1,r:180,sX:9,sY:9}],
              [{b:-1,d:1,o:-1,r:180,sX:-0.5,sY:-0.5},{b:9000,d:500,o:1,r:180,sX:0.5,sY:0.5},{b:9500,d:500,o:-1,r:180,sX:9,sY:9}]
            ];
            
            var jssor_1_options = {
              $AutoPlay: true,
              $SlideDuration: 800,
              $SlideEasing: $Jease$.$OutQuint,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $TransitionsOrder: 1
              },
              $CaptionSliderOptions: {
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
              }
            };
            
            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
                        
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizing
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 625);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>

    <style>
        
        /* jssor slider bullet navigator skin 05 css */
        /*
        .jssorb05 div           (normal)
        .jssorb05 div:hover     (normal mouseover)
        .jssorb05 .av           (active)
        .jssorb05 .av:hover     (active mouseover)
        .jssorb05 .dn           (mousedown)
        .jssorb05 {
        */
            position: absolute;
        }
        .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
            position: absolute;
            /* size of bullet elment */
            width: 16px;
            height: 16px;
            background: url('/static/images/b05.png') no-repeat;
            overflow: hidden;
            cursor: pointer;
        }
        .jssorb05 div { background-position: -7px -7px; }
        .jssorb05 div:hover, .jssorb05 .av:hover { background-position: -37px -7px; }
        .jssorb05 .av { background-position: -67px -7px; }
        .jssorb05 .dn, .jssorb05 .dn:hover { background-position: -97px -7px; }

        /* jssor slider arrow navigator skin 22 css */
        /*
        .jssora22l                  (normal)
        .jssora22r                  (normal)
        .jssora22l:hover            (normal mouseover)
        .jssora22r:hover            (normal mouseover)
        .jssora22l.jssora22ldn      (mousedown)
        .jssora22r.jssora22rdn      (mousedown)
        */
        .jssora22l, .jssora22r {
            display: block;
            position: absolute;
            /* size of arrow element */
            width: 40px;
            height: 58px;
            cursor: pointer;
            background: url('/static/images/a22.png') center center no-repeat;
            overflow: hidden;
        }
        .jssora22l { background-position: -10px -31px; }
        .jssora22r { background-position: -70px -31px; }
        .jssora22l:hover { background-position: -130px -31px; }
        .jssora22r:hover { background-position: -190px -31px; }
        .jssora22l.jssora22ldn { background-position: -2350px -31px; }
        .jssora22r.jssora22rdn { background-position: -310px -31px; }
    </style>


	%from bottle import route,error,template,run,request,get,post,static_file,redirect,response
	%import pymongo
	%import os
	%from os import listdir
	%import gridfs
	%import bottle
	%count = 0
	%i = 0
	%total = len(os.walk('/var/www/html/static/images/data4/').next()[2])
	%if(total != 0):

		<video width="600" height="340" controls style="float:left;  border-radius: 10px;">
			<source src={{videoname}} type="video/mp4">
			Browser doesn't support the video.
		</video>
	
    <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 625px; height: 340px; overflow: hidden; visibility: hidden; border-radius: 10px;">
        <!-- Loading Screen -->
        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('/static/images/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
        </div>
        <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 625px; height: 340px; overflow: hidden; border-radius: 10px;">


	%	for f in sorted(listdir('/var/www/html/static/images/data4/')):
	%		count = total - i
	%		path = 'static/images/data4/'+f	


            <div data-b={{i}} data-p="170.00" style="display: none;">
                <img data-u="image" src={{path}} />
                <div data-u="caption" data-t="1" style="position: absolute; top: 290px; left: 55px; width: 520px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">{{var[i][0].upper()+var[i][1:]}}.</div>
            </div>




	%		i = i+1
	%	end
        </div>
        <!-- Arrow Navigator -->
        <span data-u="arrowleft" class="jssora22l" style="top:0px;left:10px;width:40px;height:58px;" data-autocenter="2"></span>
        <span data-u="arrowright" class="jssora22r" style="top:0px;right:10px;width:40px;height:58px;" data-autocenter="2"></span>
        <a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
    </div>


    <!-- #endregion Jssor Slider End -->
	%end

	%if(total == 0):
		<video width="600" height="340" controls style="border-radius: 10px;">
			<source src="/static/videos/Project_video.mp4" type="video/mp4">
		</video>
	<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
	%end

	</main><! --/main -->

	</body>
</html>
